from __future__ import absolute_import

# import apis into api package
from .cancel_api import CancelApi
from .connections_api import ConnectionsApi
from .do_is_api import DOIsApi
from .datasets_api import DatasetsApi
from .describe_api import DescribeApi
from .download_api import DownloadApi
from .insights_api import InsightsApi
from .metadata_api import MetadataApi
from .metadataanalysis_api import MetadataanalysisApi
from .metadatacollections_api import MetadatacollectionsApi
from .metadatadatasources_api import MetadatadatasourcesApi
from .metadataglossary_api import MetadataglossaryApi
from .metadatarelationships_api import MetadatarelationshipsApi
from .partners_api import PartnersApi
from .projects_api import ProjectsApi
from .properties_api import PropertiesApi
from .queries_api import QueriesApi
from .requests_api import RequestsApi
from .search_api import SearchApi
from .serviceaccount_api import ServiceaccountApi
from .sparql_api import SparqlApi
from .sql_api import SqlApi
from .streams_api import StreamsApi
from .uploads_api import UploadsApi
from .user_api import UserApi
from .users_api import UsersApi
