# coding: utf-8

"""
    data.world Public API (internal version)

    This is the internal version of the Swagger API generated from the Java                                             resource objects and is not visible to external users. It must be a superset                                             of the more user-friendly Swagger API maintained manually at                                             https://github.com/datadotworld/dwapi-spec.

    OpenAPI spec version: 0.21.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CreateAnalysisContribution(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'contribution_hydratables': 'list[ContributionHydratable]',
        'catalog_iri': 'str',
        'subclass': 'str',
        'name': 'str'
    }

    attribute_map = {
        'contribution_hydratables': 'contributionHydratables',
        'catalog_iri': 'catalogIri',
        'subclass': 'subclass',
        'name': 'name'
    }

    def __init__(self, contribution_hydratables=None, catalog_iri=None, subclass=None, name=None):
        """
        CreateAnalysisContribution - a model defined in Swagger
        """

        self._contribution_hydratables = None
        self._catalog_iri = None
        self._subclass = None
        self._name = None

        if contribution_hydratables is not None:
          self.contribution_hydratables = contribution_hydratables
        self.catalog_iri = catalog_iri
        if subclass is not None:
          self.subclass = subclass
        self.name = name

    @property
    def contribution_hydratables(self):
        """
        Gets the contribution_hydratables of this CreateAnalysisContribution.

        :return: The contribution_hydratables of this CreateAnalysisContribution.
        :rtype: list[ContributionHydratable]
        """
        return self._contribution_hydratables

    @contribution_hydratables.setter
    def contribution_hydratables(self, contribution_hydratables):
        """
        Sets the contribution_hydratables of this CreateAnalysisContribution.

        :param contribution_hydratables: The contribution_hydratables of this CreateAnalysisContribution.
        :type: list[ContributionHydratable]
        """

        self._contribution_hydratables = contribution_hydratables

    @property
    def catalog_iri(self):
        """
        Gets the catalog_iri of this CreateAnalysisContribution.

        :return: The catalog_iri of this CreateAnalysisContribution.
        :rtype: str
        """
        return self._catalog_iri

    @catalog_iri.setter
    def catalog_iri(self, catalog_iri):
        """
        Sets the catalog_iri of this CreateAnalysisContribution.

        :param catalog_iri: The catalog_iri of this CreateAnalysisContribution.
        :type: str
        """
        if catalog_iri is None:
            raise ValueError("Invalid value for `catalog_iri`, must not be `None`")

        self._catalog_iri = catalog_iri

    @property
    def subclass(self):
        """
        Gets the subclass of this CreateAnalysisContribution.

        :return: The subclass of this CreateAnalysisContribution.
        :rtype: str
        """
        return self._subclass

    @subclass.setter
    def subclass(self, subclass):
        """
        Sets the subclass of this CreateAnalysisContribution.

        :param subclass: The subclass of this CreateAnalysisContribution.
        :type: str
        """

        self._subclass = subclass

    @property
    def name(self):
        """
        Gets the name of this CreateAnalysisContribution.

        :return: The name of this CreateAnalysisContribution.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this CreateAnalysisContribution.

        :param name: The name of this CreateAnalysisContribution.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CreateAnalysisContribution):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
