# coding: utf-8

"""
    data.world Public API (internal version)

    This is the internal version of the Swagger API generated from the Java                                             resource objects and is not visible to external users. It must be a superset                                             of the more user-friendly Swagger API maintained manually at                                             https://github.com/datadotworld/dwapi-spec.

    OpenAPI spec version: 0.21.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class EntryType(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'label': 'str',
        'plural_label': 'str',
        'type': 'str'
    }

    attribute_map = {
        'label': 'label',
        'plural_label': 'pluralLabel',
        'type': 'type'
    }

    def __init__(self, label=None, plural_label=None, type=None):
        """
        EntryType - a model defined in Swagger
        """

        self._label = None
        self._plural_label = None
        self._type = None

        if label is not None:
          self.label = label
        if plural_label is not None:
          self.plural_label = plural_label
        if type is not None:
          self.type = type

    @property
    def label(self):
        """
        Gets the label of this EntryType.

        :return: The label of this EntryType.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """
        Sets the label of this EntryType.

        :param label: The label of this EntryType.
        :type: str
        """

        self._label = label

    @property
    def plural_label(self):
        """
        Gets the plural_label of this EntryType.

        :return: The plural_label of this EntryType.
        :rtype: str
        """
        return self._plural_label

    @plural_label.setter
    def plural_label(self, plural_label):
        """
        Sets the plural_label of this EntryType.

        :param plural_label: The plural_label of this EntryType.
        :type: str
        """

        self._plural_label = plural_label

    @property
    def type(self):
        """
        Gets the type of this EntryType.

        :return: The type of this EntryType.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this EntryType.

        :param type: The type of this EntryType.
        :type: str
        """

        self._type = type

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, EntryType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
