# coding: utf-8

"""
    data.world Public API (internal version)

    This is the internal version of the Swagger API generated from the Java                                             resource objects and is not visible to external users. It must be a superset                                             of the more user-friendly Swagger API maintained manually at                                             https://github.com/datadotworld/dwapi-spec.

    OpenAPI spec version: 0.21.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Instant(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'nano': 'int',
        'epoch_second': 'int'
    }

    attribute_map = {
        'nano': 'nano',
        'epoch_second': 'epochSecond'
    }

    def __init__(self, nano=None, epoch_second=None):
        """
        Instant - a model defined in Swagger
        """

        self._nano = None
        self._epoch_second = None

        if nano is not None:
          self.nano = nano
        if epoch_second is not None:
          self.epoch_second = epoch_second

    @property
    def nano(self):
        """
        Gets the nano of this Instant.

        :return: The nano of this Instant.
        :rtype: int
        """
        return self._nano

    @nano.setter
    def nano(self, nano):
        """
        Sets the nano of this Instant.

        :param nano: The nano of this Instant.
        :type: int
        """

        self._nano = nano

    @property
    def epoch_second(self):
        """
        Gets the epoch_second of this Instant.

        :return: The epoch_second of this Instant.
        :rtype: int
        """
        return self._epoch_second

    @epoch_second.setter
    def epoch_second(self, epoch_second):
        """
        Sets the epoch_second of this Instant.

        :param epoch_second: The epoch_second of this Instant.
        :type: int
        """

        self._epoch_second = epoch_second

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Instant):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
