# coding: utf-8

"""
    data.world Public API (internal version)

    This is the internal version of the Swagger API generated from the Java                                             resource objects and is not visible to external users. It must be a superset                                             of the more user-friendly Swagger API maintained manually at                                             https://github.com/datadotworld/dwapi-spec.

    OpenAPI spec version: 0.21.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class RemoveUsesDataFromContribution(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'contribution_hydratables': 'list[ContributionHydratable]',
        'override_type': 'str',
        'analysis_iri': 'str',
        'table_iri': 'str'
    }

    attribute_map = {
        'contribution_hydratables': 'contributionHydratables',
        'override_type': 'overrideType',
        'analysis_iri': 'analysisIri',
        'table_iri': 'tableIri'
    }

    def __init__(self, contribution_hydratables=None, override_type=None, analysis_iri=None, table_iri=None):
        """
        RemoveUsesDataFromContribution - a model defined in Swagger
        """

        self._contribution_hydratables = None
        self._override_type = None
        self._analysis_iri = None
        self._table_iri = None

        if contribution_hydratables is not None:
          self.contribution_hydratables = contribution_hydratables
        if override_type is not None:
          self.override_type = override_type
        self.analysis_iri = analysis_iri
        self.table_iri = table_iri

    @property
    def contribution_hydratables(self):
        """
        Gets the contribution_hydratables of this RemoveUsesDataFromContribution.

        :return: The contribution_hydratables of this RemoveUsesDataFromContribution.
        :rtype: list[ContributionHydratable]
        """
        return self._contribution_hydratables

    @contribution_hydratables.setter
    def contribution_hydratables(self, contribution_hydratables):
        """
        Sets the contribution_hydratables of this RemoveUsesDataFromContribution.

        :param contribution_hydratables: The contribution_hydratables of this RemoveUsesDataFromContribution.
        :type: list[ContributionHydratable]
        """

        self._contribution_hydratables = contribution_hydratables

    @property
    def override_type(self):
        """
        Gets the override_type of this RemoveUsesDataFromContribution.

        :return: The override_type of this RemoveUsesDataFromContribution.
        :rtype: str
        """
        return self._override_type

    @override_type.setter
    def override_type(self, override_type):
        """
        Sets the override_type of this RemoveUsesDataFromContribution.

        :param override_type: The override_type of this RemoveUsesDataFromContribution.
        :type: str
        """
        allowed_values = ["SET", "ADD", "REMOVE"]
        if override_type not in allowed_values:
            raise ValueError(
                "Invalid value for `override_type` ({0}), must be one of {1}"
                .format(override_type, allowed_values)
            )

        self._override_type = override_type

    @property
    def analysis_iri(self):
        """
        Gets the analysis_iri of this RemoveUsesDataFromContribution.

        :return: The analysis_iri of this RemoveUsesDataFromContribution.
        :rtype: str
        """
        return self._analysis_iri

    @analysis_iri.setter
    def analysis_iri(self, analysis_iri):
        """
        Sets the analysis_iri of this RemoveUsesDataFromContribution.

        :param analysis_iri: The analysis_iri of this RemoveUsesDataFromContribution.
        :type: str
        """
        if analysis_iri is None:
            raise ValueError("Invalid value for `analysis_iri`, must not be `None`")

        self._analysis_iri = analysis_iri

    @property
    def table_iri(self):
        """
        Gets the table_iri of this RemoveUsesDataFromContribution.

        :return: The table_iri of this RemoveUsesDataFromContribution.
        :rtype: str
        """
        return self._table_iri

    @table_iri.setter
    def table_iri(self, table_iri):
        """
        Sets the table_iri of this RemoveUsesDataFromContribution.

        :param table_iri: The table_iri of this RemoveUsesDataFromContribution.
        :type: str
        """
        if table_iri is None:
            raise ValueError("Invalid value for `table_iri`, must not be `None`")

        self._table_iri = table_iri

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, RemoveUsesDataFromContribution):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
