# coding: utf-8

"""
    data.world Public API (internal version)

    This is the internal version of the Swagger API generated from the Java                                             resource objects and is not visible to external users. It must be a superset                                             of the more user-friendly Swagger API maintained manually at                                             https://github.com/datadotworld/dwapi-spec.

    OpenAPI spec version: 0.21.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class SingleTableMetadataSpecDto(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'database': 'str',
        'schema': 'str',
        'table': 'str',
        'table_type': 'str'
    }

    attribute_map = {
        'database': 'database',
        'schema': 'schema',
        'table': 'table',
        'table_type': 'tableType'
    }

    def __init__(self, database=None, schema=None, table=None, table_type=None):
        """
        SingleTableMetadataSpecDto - a model defined in Swagger
        """

        self._database = None
        self._schema = None
        self._table = None
        self._table_type = None

        if database is not None:
          self.database = database
        if schema is not None:
          self.schema = schema
        if table is not None:
          self.table = table
        if table_type is not None:
          self.table_type = table_type

    @property
    def database(self):
        """
        Gets the database of this SingleTableMetadataSpecDto.

        :return: The database of this SingleTableMetadataSpecDto.
        :rtype: str
        """
        return self._database

    @database.setter
    def database(self, database):
        """
        Sets the database of this SingleTableMetadataSpecDto.

        :param database: The database of this SingleTableMetadataSpecDto.
        :type: str
        """

        self._database = database

    @property
    def schema(self):
        """
        Gets the schema of this SingleTableMetadataSpecDto.

        :return: The schema of this SingleTableMetadataSpecDto.
        :rtype: str
        """
        return self._schema

    @schema.setter
    def schema(self, schema):
        """
        Sets the schema of this SingleTableMetadataSpecDto.

        :param schema: The schema of this SingleTableMetadataSpecDto.
        :type: str
        """

        self._schema = schema

    @property
    def table(self):
        """
        Gets the table of this SingleTableMetadataSpecDto.

        :return: The table of this SingleTableMetadataSpecDto.
        :rtype: str
        """
        return self._table

    @table.setter
    def table(self, table):
        """
        Sets the table of this SingleTableMetadataSpecDto.

        :param table: The table of this SingleTableMetadataSpecDto.
        :type: str
        """

        self._table = table

    @property
    def table_type(self):
        """
        Gets the table_type of this SingleTableMetadataSpecDto.

        :return: The table_type of this SingleTableMetadataSpecDto.
        :rtype: str
        """
        return self._table_type

    @table_type.setter
    def table_type(self, table_type):
        """
        Sets the table_type of this SingleTableMetadataSpecDto.

        :param table_type: The table_type of this SingleTableMetadataSpecDto.
        :type: str
        """
        allowed_values = ["EXTRACT", "VIRTUAL"]
        if table_type not in allowed_values:
            raise ValueError(
                "Invalid value for `table_type` ({0}), must be one of {1}"
                .format(table_type, allowed_values)
            )

        self._table_type = table_type

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SingleTableMetadataSpecDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
