# coding: utf-8

"""
    data.world Public API (internal version)

    This is the internal version of the Swagger API generated from the Java                                             resource objects and is not visible to external users. It must be a superset                                             of the more user-friendly Swagger API maintained manually at                                             https://github.com/datadotworld/dwapi-spec.

    OpenAPI spec version: 0.21.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class SqlQueryRequest(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'query': 'str',
        'include_table_schema': 'bool',
        'dataset_versions': 'str',
        'query_run_token': 'str'
    }

    attribute_map = {
        'query': 'query',
        'include_table_schema': 'includeTableSchema',
        'dataset_versions': 'datasetVersions',
        'query_run_token': 'queryRunToken'
    }

    def __init__(self, query=None, include_table_schema=False, dataset_versions=None, query_run_token=None):
        """
        SqlQueryRequest - a model defined in Swagger
        """

        self._query = None
        self._include_table_schema = None
        self._dataset_versions = None
        self._query_run_token = None

        self.query = query
        if include_table_schema is not None:
          self.include_table_schema = include_table_schema
        if dataset_versions is not None:
          self.dataset_versions = dataset_versions
        if query_run_token is not None:
          self.query_run_token = query_run_token

    @property
    def query(self):
        """
        Gets the query of this SqlQueryRequest.

        :return: The query of this SqlQueryRequest.
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """
        Sets the query of this SqlQueryRequest.

        :param query: The query of this SqlQueryRequest.
        :type: str
        """
        if query is None:
            raise ValueError("Invalid value for `query`, must not be `None`")

        self._query = query

    @property
    def include_table_schema(self):
        """
        Gets the include_table_schema of this SqlQueryRequest.

        :return: The include_table_schema of this SqlQueryRequest.
        :rtype: bool
        """
        return self._include_table_schema

    @include_table_schema.setter
    def include_table_schema(self, include_table_schema):
        """
        Sets the include_table_schema of this SqlQueryRequest.

        :param include_table_schema: The include_table_schema of this SqlQueryRequest.
        :type: bool
        """

        self._include_table_schema = include_table_schema

    @property
    def dataset_versions(self):
        """
        Gets the dataset_versions of this SqlQueryRequest.

        :return: The dataset_versions of this SqlQueryRequest.
        :rtype: str
        """
        return self._dataset_versions

    @dataset_versions.setter
    def dataset_versions(self, dataset_versions):
        """
        Sets the dataset_versions of this SqlQueryRequest.

        :param dataset_versions: The dataset_versions of this SqlQueryRequest.
        :type: str
        """

        self._dataset_versions = dataset_versions

    @property
    def query_run_token(self):
        """
        Gets the query_run_token of this SqlQueryRequest.

        :return: The query_run_token of this SqlQueryRequest.
        :rtype: str
        """
        return self._query_run_token

    @query_run_token.setter
    def query_run_token(self, query_run_token):
        """
        Sets the query_run_token of this SqlQueryRequest.

        :param query_run_token: The query_run_token of this SqlQueryRequest.
        :type: str
        """

        self._query_run_token = query_run_token

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SqlQueryRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
