version: 2
jobs:
  build:
    working_directory: /root/data.world-py

    environment:
      PRERELEASE_BRANCH: prerelease
      RELEASE_BRANCH: release

    steps:
      - restore_cache:
          keys:
            - main_cache

      - run:
          name: install dependencies
          command: |
            pyenv global 2.7.11 3.4.4 3.5.1 3.6.0
            pip install tox twine

      - run:
          name: tox
          command: tox

      - deploy:
          name: pre-release to pypi
          command: |
            if [[ ! "${CIRCLE_BRANCH}" =~ ^${PRERELEASE_BRANCH}$ ]]; then
              # twine command for pre-release
            fi

      - deploy:
          name: release to pypi
          command: |
            if [[ ! "${CIRCLE_BRANCH}" =~ ^${RELEASE_BRANCH}$ ]]; then
              python setup.py sdist
              twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
            fi

      - save_cache:
          key: main_cache
          paths:
            - .eggs
            - .tox
