version: 2
jobs:
  build:
    docker:
      - image: dataworld/pyenv

    working_directory: ~/data.world-py

    environment:
      PRERELEASE_BRANCH: prerelease
      RELEASE_BRANCH: release

    steps:
      - run: env

      - checkout

      - restore_cache:
          keys:
            - main_cache

      - run:
          name: pyenv setup
          command: |
            eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)"
            pyenv global 2.7.13 3.4.5 3.5.2 3.6.0
            tox -r -e python34

      - run:
          name: tox
          command: tox

      - save_cache:
          key: main_cache
          paths:
            - .eggs
            - .tox

      - deploy:
          name: Pre-release to pypi
          command: |
            if [[ "${CIRCLE_BRANCH}" =~ ^(${PRERELEASE_BRANCH})$ ]]; then
              echo 'Do a prerelease with twine here'
            fi

      - deploy:
          name: Release to pypi
          command: |
            if [[ "${CIRCLE_BRANCH}" =~ ^(${RELEASE_BRANCH})$ ]]; then
              python setup.py sdist
              twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
            fi
